# Generated by Django 5.2.8 on 2026-01-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='token_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
