# Generated by Django 5.2.8 on 2026-01-10 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0001_initial'),
        ('user', '0004_alter_user_tbl_email_alter_user_tbl_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('BP', 'Blood Pressure'), ('SUGAR', 'Blood Sugar'), ('BLOOD', 'Blood Test'), ('URINE', 'Urine Test'), ('OTHER', 'Other')], max_length=20)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='lab_reports/')),
                ('report_date', models.DateField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_tbl')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_file', models.FileField(blank=True, null=True, upload_to='prescriptions/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointment.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_tbl')),
            ],
        ),
        migrations.CreateModel(
            name='ScanReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('XRAY', 'X-Ray'), ('MRI', 'MRI'), ('CT', 'CT Scan'), ('ULTRASOUND', 'Ultrasound'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('scan_file', models.FileField(upload_to='scan_reports/')),
                ('scan_date', models.DateField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_tbl')),
            ],
        ),
    ]
