# Generated by Django 5.2.8 on 2025-12-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_doctor_tbl_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_tbl',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor_tbl',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
