# Generated by Django 5.2.8 on 2026-01-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_alter_doctor_tbl_email_alter_doctor_tbl_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_tbl',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='doctor_tbl',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
