# Generated by Django 5.2.8 on 2026-01-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_alter_doctor_tbl_email_alter_doctor_tbl_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_tbl',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_photos/'),
        ),
    ]
