# Generated by Django 5.2.8 on 2025-12-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_tbl_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_tbl',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
