# Generated by Django 5.2.8 on 2025-12-30 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_tbl',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='user_tbl',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='user_tbl',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='user_tbl',
            name='specialization',
        ),
    ]
