# Generated by Django 5.2.8 on 2025-12-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0002_delete_doctor_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=150)),
                ('experience', models.PositiveIntegerField()),
                ('phone_number', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('is_approved', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Waiting', 'Waiting')], default='Waiting', max_length=20)),
            ],
        ),
    ]
