# Generated by Django 5.2.8 on 2026-01-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_doctor_tbl_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_tbl',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100),
        ),
    ]
