# Generated by Django 5.2.8 on 2026-01-07 14:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_alter_doctoravailability_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_tbl',
            name='auth_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
