# Generated by Django 5.2.8 on 2026-01-07 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_doctor_tbl_auth_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor_tbl',
            name='auth_token',
        ),
    ]
